// // This file is auto-generated by Lovable. Do not modify it.

// import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
// import { supabase } from "../supabase/client";
// const lovableAuth = createLovableAuth();

// type SignInOptions = {
//   redirect_uri?: string;
//   extraParams?: Record<string, string>;
// };

// export const lovable = {
//   auth: {
//     signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
//       const result = await lovableAuth.signInWithOAuth(provider, {
//         redirect_uri: opts?.redirect_uri,
//         extraParams: {
//           ...opts?.extraParams,
//         },
//       });

//       if (result.redirected) {
//         return result;
//       }

//       if (result.error) {
//         return result;
//       }

//       try {
//         await supabase.auth.setSession(result.tokens);
//       } catch (e) {
//         return { error: e instanceof Error ? e : new Error(String(e)) };
//       }
//       return result;
//     },
//   },
// };


import { supabase } from "../supabase/client";

type SignInOptions = {
  redirectTo?: string;
  queryParams?: Record<string, string>;
};

export const auth = {
  signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
    return supabase.auth.signInWithOAuth({
      provider,
      options: {
        redirectTo: opts?.redirectTo,          // URL a la que vuelve el provider
        queryParams: opts?.queryParams,        // params extra opcionales
      },
    });
  },

  signOut: async () => supabase.auth.signOut(),

  getUser: async () => supabase.auth.getUser(),

  onAuthStateChange: (cb: Parameters<typeof supabase.auth.onAuthStateChange>[0]) =>
    supabase.auth.onAuthStateChange(cb),
};